#version: '3.8'
#services:
#  postgres:
#    restart: always
#    image: postgres
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    ports:
#      - 5432:5432

services:
  main:
    container_name: main
    build:
      context: .
    ports:
      - 4000:4000
    command: npm run start:dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:123@localhost:5432/nest?schema=public?connect_timeout=300
    depends_on:
      - postgres
  postgres:
    container_name: ps
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

