services:
  main:
    restart: always
    container_name: main
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run start:dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres:5432/nest?schema=public&connect_timeout=300
    depends_on:
      - postgres
    networks:
      - net
  postgres:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: ps
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - net
    volumes:
      - /var/lib/postgresql/data

networks:
  net:
    driver: bridge
