-- AlterTable
ALTER TABLE "User" ALTER COLUMN "version" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3);
DROP SEQUENCE "User_version_seq";
